/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    PaymentEscrow: {
      address: "0x85a038f7FB8E01EBD6F0E5B02791E57Bfb6aa260",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "DeadlineExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "DeadlineNotReached",
          type: "error",
        },
        {
          inputs: [],
          name: "DirectFundingDisabled",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "received",
              type: "uint256",
            },
          ],
          name: "IncorrectFunding",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAmount",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidDeadline",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "InvalidPayment",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              internalType: "enum PaymentEscrow.State",
              name: "currentState",
              type: "uint8",
            },
          ],
          name: "InvalidState",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "Unauthorized",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payee",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "arbiter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "createdAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "deadline",
              type: "uint64",
            },
          ],
          name: "PaymentCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "asset",
              type: "address",
            },
          ],
          name: "PaymentFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "asset",
              type: "address",
            },
          ],
          name: "PaymentRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payee",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "asset",
              type: "address",
            },
          ],
          name: "PaymentReleased",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "payee",
              type: "address",
            },
            {
              internalType: "address",
              name: "arbiter",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "deadline",
              type: "uint64",
            },
          ],
          name: "createPayment",
          outputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "fundPayment",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "getPayment",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "payer",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "payee",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "arbiter",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "asset",
                  type: "address",
                },
                {
                  internalType: "uint64",
                  name: "createdAt",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "deadline",
                  type: "uint64",
                },
                {
                  internalType: "enum PaymentEscrow.State",
                  name: "state",
                  type: "uint8",
                },
              ],
              internalType: "struct PaymentEscrow.Payment",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextPaymentId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "refundPayment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "releasePayment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalEscrowed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41305503,
    },
    TokenPaymentEscrow: {
      address: "0xa1069144BAc92E69634F8af332C92d053d9e72bb",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "DeadlineExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
          ],
          name: "DeadlineNotReached",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "received",
              type: "uint256",
            },
          ],
          name: "IncorrectTokenReceived",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAmount",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidDeadline",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "InvalidPayment",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              internalType: "enum TokenPaymentEscrow.State",
              name: "currentState",
              type: "uint8",
            },
          ],
          name: "InvalidState",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "InvalidToken",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "responseCode",
              type: "uint256",
            },
          ],
          name: "InvalidTokenResponse",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TokenTransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "Unauthorized",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "EscrowTokenAssociated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "payee",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "arbiter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "createdAt",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "deadline",
              type: "uint64",
            },
          ],
          name: "TokenPaymentCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TokenPaymentFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TokenPaymentRefunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payee",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "TokenPaymentReleased",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "associateToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              internalType: "address",
              name: "payee",
              type: "address",
            },
            {
              internalType: "address",
              name: "arbiter",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint64",
              name: "deadline",
              type: "uint64",
            },
          ],
          name: "createPayment",
          outputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "fundPayment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "getPayment",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "payer",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "payee",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "arbiter",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "token",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "uint64",
                  name: "createdAt",
                  type: "uint64",
                },
                {
                  internalType: "uint64",
                  name: "deadline",
                  type: "uint64",
                },
                {
                  internalType: "enum TokenPaymentEscrow.State",
                  name: "state",
                  type: "uint8",
                },
              ],
              internalType: "struct TokenPaymentEscrow.Payment",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nextPaymentId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "refundPayment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "paymentId",
              type: "uint256",
            },
          ],
          name: "releasePayment",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "totalEscrowed",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41308091,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
